name: Release builder

on:
  release:
    types: [created]
  push:

jobs:
  release_build:
    runs-on: ubuntu-latest
    steps:
    - name: "Install hub"
      run: "sudo snap install hub --classic"
    - name: "Checkout repository"
      uses: actions/checkout@master
    - name: "Composer install"
      uses: MilesChou/composer-action@master
      with:
        args: install --ignore-platform-reqs
    - name: "Move Pelago_Emogrifier to /lib"
      run: "mkdir -p lib/Pelago/Emogrifier; mv vendor/pelago/emogrifier/src/* lib/Pelago/Emogrifier/"
    - name: "Cleanup"
      run: "rm -rf vendor; git checkout composer.json composer.lock app/Mage.php"
