name: Release builder

on:
  release:
    types: [created]
  push:

jobs:
  release_build:
    runs-on: ubuntu-latest
    steps:
    - name: "Install hub"
      run: "sudo snap install hub --classic"
    - name: "Checkout repository"
      uses: actions/checkout@master
    - name: "Composer install"
      uses: MilesChou/composer-action@master
      with:
        args: install --ignore-platform-reqs
    - name: "Move Pelago_Emogrifier to /lib"
      run: "mkdir -p lib/Pelago/Emogrifier; cp -R vendor/pelago/emogrifier/src/* lib/Pelago/Emogrifier/"
    - name: "Move Cm_RedisSession to /lib and /app"
      run: "mkdir -p lib/Credis; cp -R vendor/colinmollenhour/credis/* lib/Credis/; mkdir -p app/code/local/Cm/RedisSession; cp -R vendor/colinmollenhour/magento-redis-session/app/code/local/Cm/RedisSession/* app/code/local/Cm/RedisSession/"
    - name: "Cleanup"
      run: "sudo rm -rf vendor; git checkout composer.json composer.lock app/Mage.php"
