name: Release builder

on:
  release:
    types: [created]

jobs:
  release_build:
    runs-on: ubuntu-latest
    steps:
    - name: "Install hub"
      run: "sudo snap install hub --classic"
    - name: "Checkout repository"
      uses: actions/checkout@master
    - name: "Composer install"
      uses: MilesChou/composer-action@master
      with:
        args: install --ignore-platform-reqs
    - name: "Move Pelago_Emogrifier to /lib"
      run: "mkdir -p lib/Pelago/Emogrifier; cp -R vendor/pelago/emogrifier/src/* lib/Pelago/Emogrifier/"
    - name: "Move Cm_RedisSession to /lib and /app"
      run: "mkdir -p lib/Credis; cp -R vendor/colinmollenhour/credis/* lib/Credis/; mkdir -p app/code/community/Cm/RedisSession; cp -R vendor/colinmollenhour/magento-redis-session/app/code/local/Cm/RedisSession/* app/code/community/Cm/RedisSession/"
    - name: "Create Cm_RedisSession in app/etc/modules"
      run: "echo '<config><modules><Cm_RedisSession><active>false</active><codePool>community</codePool></Cm_RedisSession></modules></config>'>app/etc/modules/Cm_RedisSession.xml"
    - name: "Cleanup"
      run: "git checkout composer.json composer.lock app/Mage.php; sudo rm -rf root vendor"
    - name: "Create ZIP file"
      run: zip -rq ${{ github.event.release.tag_name }}.zip . -x .git
    - name: "Attach ZIP to GitHub release"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: hub release edit ${{ github.event.release.tag_name }} --attach ${{ github.event.release.tag_name }}.zip
